import 'package:cloud_firestore/cloud_firestore.dart';

class InstituteSettingsModel {
  const InstituteSettingsModel({
    required this.id,
    required this.instituteName,
    required this.ownerName,
    required this.address,
    required this.phone,
    required this.whatsappNumber,
    required this.email,
    required this.website,
    required this.logoUrl,
    required this.signatureUrl,
    required this.defaultCountryCode,
    required this.academicYear,
    required this.receiptPrefix,
    required this.receiptFooter,
    required this.reportFooter,
    required this.currencySymbol,
    required this.timezone,
    required this.themeMode,
    required this.primaryColorName,
    required this.feeReminderDaysBefore,
    required this.birthdayReminderDaysBefore,
    this.createdAt,
    this.updatedAt,
  });

  final String id;
  final String instituteName;
  final String ownerName;
  final String address;
  final String phone;
  final String whatsappNumber;
  final String email;
  final String website;
  final String logoUrl;
  final String signatureUrl;
  final String defaultCountryCode;
  final String academicYear;
  final String receiptPrefix;
  final String receiptFooter;
  final String reportFooter;
  final String currencySymbol;
  final String timezone;
  final String themeMode;
  final String primaryColorName;
  final int feeReminderDaysBefore;
  final int birthdayReminderDaysBefore;
  final DateTime? createdAt;
  final DateTime? updatedAt;

  factory InstituteSettingsModel.defaults() {
    final year = DateTime.now().year;
    return InstituteSettingsModel(
      id: 'institute',
      instituteName: 'Mak Tutorials',
      ownerName: '',
      address: '',
      phone: '',
      whatsappNumber: '',
      email: '',
      website: '',
      logoUrl: '',
      signatureUrl: '',
      defaultCountryCode: '91',
      academicYear: '$year-${(year + 1).toString().substring(2)}',
      receiptPrefix: 'MT',
      receiptFooter: 'This is a computer-generated receipt.',
      reportFooter: 'Generated by Mak Tutorials Classes Management App.',
      currencySymbol: 'Rs',
      timezone: 'Asia/Kolkata',
      themeMode: 'light',
      primaryColorName: 'blue',
      feeReminderDaysBefore: 3,
      birthdayReminderDaysBefore: 7,
    );
  }

  factory InstituteSettingsModel.fromMap(String id, Map<String, dynamic> data) {
    final defaults = InstituteSettingsModel.defaults();
    return InstituteSettingsModel(
      id: id,
      instituteName:
          _string(data['instituteName'] ?? data['institute_name']) ??
          defaults.instituteName,
      ownerName: _string(data['ownerName'] ?? data['owner_name']) ?? '',
      address: _string(data['address']) ?? '',
      phone:
          _string(data['phone'] ?? data['contact_number'] ?? data['mobile']) ??
          '',
      whatsappNumber:
          _string(data['whatsappNumber'] ?? data['whatsapp_number']) ?? '',
      email: _string(data['email']) ?? '',
      website: _string(data['website']) ?? '',
      logoUrl: _string(data['logoUrl'] ?? data['logo_url']) ?? '',
      signatureUrl:
          _string(data['signatureUrl'] ?? data['signature_url']) ?? '',
      defaultCountryCode:
          _string(data['defaultCountryCode'] ?? data['default_country_code']) ??
          defaults.defaultCountryCode,
      academicYear:
          _string(data['academicYear'] ?? data['academic_year']) ??
          defaults.academicYear,
      receiptPrefix:
          _string(data['receiptPrefix'] ?? data['receipt_prefix']) ??
          defaults.receiptPrefix,
      receiptFooter:
          _string(data['receiptFooter'] ?? data['receipt_footer']) ??
          defaults.receiptFooter,
      reportFooter:
          _string(data['reportFooter'] ?? data['report_footer']) ??
          defaults.reportFooter,
      currencySymbol:
          _string(data['currencySymbol'] ?? data['currency_symbol']) ??
          defaults.currencySymbol,
      timezone: _string(data['timezone']) ?? defaults.timezone,
      themeMode: _string(data['themeMode'] ?? data['theme_mode']) ?? 'light',
      primaryColorName:
          _string(data['primaryColorName'] ?? data['primary_color_name']) ??
          'blue',
      feeReminderDaysBefore:
          _int(
            data['feeReminderDaysBefore'] ?? data['fee_reminder_days_before'],
          ) ??
          defaults.feeReminderDaysBefore,
      birthdayReminderDaysBefore:
          _int(
            data['birthdayReminderDaysBefore'] ??
                data['birthday_reminder_days_before'],
          ) ??
          defaults.birthdayReminderDaysBefore,
      createdAt: _date(data['createdAt'] ?? data['created_at']),
      updatedAt: _date(data['updatedAt'] ?? data['updated_at']),
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'instituteName': instituteName,
      'institute_name': instituteName,
      'ownerName': ownerName,
      'address': address,
      'phone': phone,
      'contact_number': phone,
      'whatsappNumber': whatsappNumber,
      'email': email,
      'website': website,
      'logoUrl': logoUrl,
      'logo_url': logoUrl,
      'signatureUrl': signatureUrl,
      'signature_url': signatureUrl,
      'defaultCountryCode': defaultCountryCode,
      'academicYear': academicYear,
      'receiptPrefix': receiptPrefix,
      'receiptFooter': receiptFooter,
      'reportFooter': reportFooter,
      'currencySymbol': currencySymbol,
      'timezone': timezone,
      'themeMode': themeMode,
      'primaryColorName': primaryColorName,
      'feeReminderDaysBefore': feeReminderDaysBefore,
      'birthdayReminderDaysBefore': birthdayReminderDaysBefore,
      'updatedAt': FieldValue.serverTimestamp(),
      if (createdAt == null) 'createdAt': FieldValue.serverTimestamp(),
    };
  }

  InstituteSettingsModel copyWith({
    String? instituteName,
    String? ownerName,
    String? address,
    String? phone,
    String? whatsappNumber,
    String? email,
    String? website,
    String? logoUrl,
    String? signatureUrl,
    String? defaultCountryCode,
    String? academicYear,
    String? receiptPrefix,
    String? receiptFooter,
    String? reportFooter,
    String? currencySymbol,
    String? timezone,
    String? themeMode,
    String? primaryColorName,
    int? feeReminderDaysBefore,
    int? birthdayReminderDaysBefore,
  }) {
    return InstituteSettingsModel(
      id: id,
      instituteName: instituteName ?? this.instituteName,
      ownerName: ownerName ?? this.ownerName,
      address: address ?? this.address,
      phone: phone ?? this.phone,
      whatsappNumber: whatsappNumber ?? this.whatsappNumber,
      email: email ?? this.email,
      website: website ?? this.website,
      logoUrl: logoUrl ?? this.logoUrl,
      signatureUrl: signatureUrl ?? this.signatureUrl,
      defaultCountryCode: defaultCountryCode ?? this.defaultCountryCode,
      academicYear: academicYear ?? this.academicYear,
      receiptPrefix: receiptPrefix ?? this.receiptPrefix,
      receiptFooter: receiptFooter ?? this.receiptFooter,
      reportFooter: reportFooter ?? this.reportFooter,
      currencySymbol: currencySymbol ?? this.currencySymbol,
      timezone: timezone ?? this.timezone,
      themeMode: themeMode ?? this.themeMode,
      primaryColorName: primaryColorName ?? this.primaryColorName,
      feeReminderDaysBefore:
          feeReminderDaysBefore ?? this.feeReminderDaysBefore,
      birthdayReminderDaysBefore:
          birthdayReminderDaysBefore ?? this.birthdayReminderDaysBefore,
      createdAt: createdAt,
      updatedAt: DateTime.now(),
    );
  }

  static String? _string(dynamic value) {
    if (value == null) return null;
    final text = value.toString().trim();
    return text.isEmpty ? null : text;
  }

  static int? _int(dynamic value) {
    if (value == null) return null;
    if (value is int) return value;
    if (value is num) return value.toInt();
    return int.tryParse(value.toString());
  }

  static DateTime? _date(dynamic value) {
    if (value == null) return null;
    if (value is Timestamp) return value.toDate();
    if (value is DateTime) return value;
    return DateTime.tryParse(value.toString());
  }
}
