// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD9eneWkz79MJvhgxH-avItCSoQo-UAFk',
    appId: '1:1041213751936:web:f4223540a55a0eb2041c65',
    messagingSenderId: '1041213751936',
    projectId: 'classes-management-pro',
    authDomain: 'classes-management-pro.firebaseapp.com',
    storageBucket: 'classes-management-pro.firebasestorage.app',
    measurementId: 'G-Q0K85D3N9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Xn2siwTFkyNv_pZiXa-gmRkKJG-Js_k',
    appId: '1:1041213751936:android:d6e70ae6436f1783041c65',
    messagingSenderId: '1041213751936',
    projectId: 'classes-management-pro',
    storageBucket: 'classes-management-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPHJ_3Kzcux7J3sJ8VueLDQz2bgWe5F50',
    appId: '1:1041213751936:ios:e1b12c159f6b70f1041c65',
    messagingSenderId: '1041213751936',
    projectId: 'classes-management-pro',
    storageBucket: 'classes-management-pro.firebasestorage.app',
    iosBundleId: 'com.example.classesProAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPHJ_3Kzcux7J3sJ8VueLDQz2bgWe5F50',
    appId: '1:1041213751936:ios:e1b12c159f6b70f1041c65',
    messagingSenderId: '1041213751936',
    projectId: 'classes-management-pro',
    storageBucket: 'classes-management-pro.firebasestorage.app',
    iosBundleId: 'com.example.classesProAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD9eneWkz79MJvhgxH-avItCSoQo-UAFk',
    appId: '1:1041213751936:web:a798b4942ae7abd4041c65',
    messagingSenderId: '1041213751936',
    projectId: 'classes-management-pro',
    authDomain: 'classes-management-pro.firebaseapp.com',
    storageBucket: 'classes-management-pro.firebasestorage.app',
    measurementId: 'G-VR8LQX0GJF',
  );
}
